import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const manrope = Manrope({ 
  subsets: ["latin"],
  weight:"400",
  display:"swap"

 });

export const metadata: Metadata = {
  title: "Yol Arkadaşı",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Header/>
       <StoreProvider count={0}>{children}</StoreProvider>
       <Footer/>
      </body>
    </html>
  );
}
